### ISSUE TITLE
tune tutorial

### ISSUE THREAD

**Issue by leo-filgueira** [yixuan/recosystem#10]
Is there any tutorial, or something like this, about `opts` parameters, in `tune`? The description available in help is not enough.

Thanks!

**Comment by yixuan** [comment]
Do you mean the meaning of different parameters, or the usage of `tune()` itself?

**Comment by leo-filgueira** [comment]
The meaning of the parameters

**Comment by yixuan** [comment]
For tuning parameters, take a look at the loss function formula in the [vignette](https://cran.r-project.org/web/packages/recosystem/vignettes/introduction.html) and the [LibMF paper](https://www.csie.ntu.edu.tw/~cjlin/papers/libmf/libmf_open_source.pdf).

For other more technical parameters, look at the the following two papers:
1. W.-S. Chin, Y. Zhuang, Y.-C. Juan, and C.-J. Lin. [A Fast Parallel Stochastic Gradient Method for Matrix Factorization in Shared Memory Systems](https://www.csie.ntu.edu.tw/~cjlin/papers/libmf/libmf_journal.pdf). ACM TIST, 2015.
2. W.-S. Chin, Y. Zhuang, Y.-C. Juan, and C.-J. Lin. [A Learning-rate Schedule for Stochastic Gradient Methods to Matrix Factorization](https://www.csie.ntu.edu.tw/~cjlin/papers/libmf/mf_adaptive_pakdd.pdf). PAKDD, 2015.

**Comment by leo-filgueira** [comment]
Thanks
