### ISSUE TITLE
multithreading on OS X

### ISSUE THREAD

**Issue by dselivanov** [yixuan/recosystem#11]
HI @yixuan . I remember when I tried the package on my apple laptop, multithreading didn't work as expected. By "didn't work"  I mean that it compiled and run, but it was significantly slower than with single thread (i think because of thread contention and usage of some specific CPU instruction in libMF). 

So this code 
```r
library(recosystem)
set.seed(123) # This is a randomized algorithm
train_set = data_file(system.file("dat", "smalltrain.txt", package = "recosystem"))
test_set  = data_file(system.file("dat", "smalltest.txt",  package = "recosystem"))
r = Reco()

system.time(
  {
    opts = r$tune(train_set, opts = list(dim = c(10, 20, 30), lrate = c(0.1, 0.2),
                                         costp_l1 = 0, costq_l1 = 0,
                                         nthread = 1, niter = 10))
  }  
)
```
on a single thread is ~8x faster compared to 4 threads on a 4 core laptop.

On linux it works just fine. I think it worth to add warning about that behaviour.

**Comment by dselivanov** [comment]
Actually there is a paragraph about that in libMF readme:
```text
To complie LIBMF on Mac, a GCC complier is required, and users need to
    slightly modify the Makefile. The following instructions are tested with
    GCC 4.9.

    1. Set the complier path to your GCC complier. For example, the first
       line in the Makefile can be

       CXX = g++-4.9

    2. Remove `-march=native' from `CXXFLAGS.' The second line in the Makefile
       Should be

       CXXFLAGS = -O3 -pthread -std=c++0x

    3. If AVX is enabled, we add `-Wa,-q' to the `CXXFLAGS,' so the previous
       `CXXFLAGS' becomes

       CXXFLAGS = -O3 -pthread -std=c++0x -Wa,-q
```

I think it is possible to create configure file to implement this.

**Comment by yixuan** [comment]
This sounds interesting, and most likely it is related to the cost of creating a thread in different OS. Did you observe anything similar in `rsparse`?

**Comment by yixuan** [comment]
Perhaps that README doesn't explain the behavior of multi-threading. AVX can be enabled in both single-threaded and multi-threaded environments.

**Comment by dselivanov** [comment]
I've seen the problem when application use both OpenMP and multithreaded BLAS (openblas in my case). In this scenario it can be slower 1000x and more.

Not sure what is the problem here. I can try to compile it with suggested flags and see.

**Comment by dselivanov** [comment]
Unfortunately no luck - I've tried suggestions above, problem remains (I use `clang-4`). Looks like indeed it can be related to `pthread` and cost of thread creation, but I'm not an expert in such low-level details.

**Comment by yixuan** [comment]
Hi @dselivanov, I wonder if the latest version still has this problem. Feel free to reopen this issue if it still fails.
