### ISSUE TITLE
Row-oriented logistic loss for prediction

### ISSUE THREAD

**Issue by sharonwoo** [yixuan/recosystem#12]
Hi,

I am trying to use the Recosystem wrapper for experiments. But I am obtaining different results compared to using the executable. Can I check if: 

`mf-train -l1 0 -l2 0 -f 10 -k 20 -t 20 -r 0.1 train_positive.txt bpr_model.txt`
`mf-predict -e 10 testset.txt bpr_model.txt bpr_output.txt`

Is the same as 
`r$train(train, opts = list(dim =20,loss="row_log",niter=20, lrate=0.1, 
                           costp_l1 = 0.0, 
                           costq_l1 = 0.0, 
                           costp_l2 = 0.0, 
                           costq_l2 = 0.0),)`
`r$predict(test, out_file('results.txt'))`

Thanks in advance!

**Comment by yixuan** [comment]
The parameter settings should be the same, but `recosystem` uses a different random number generator, so the results would not be exactly the same. You can compare the two results. If the difference looks like some random error, you are still good.
