### ISSUE TITLE
'train' makes Rstudio crashes when setting parameter dim > 50

### ISSUE THREAD

**Issue by chanonpr** [yixuan/recosystem#14]
Hi Yixuan, thanks for your great work on this package.

I am working on a recommender system project where there are 500 item IDs and more than 1 million user IDs.

Before going with the entire data, I used the sampled data with just 100 item IDs and the training was done with the parameter 'dim' set to be 50. Everything worked fine.

However, when I scaled up to use the data with 300 item IDs and used 'dim' =c(50,100,150,300) for tuning, dim = 300 turned to provide the best result. So I trained by setting dim = 300. But this always made RStudio crashed as it said 'RStudio session aborted' and forced me to restart the program.

I tried changing other parameters' values including 'nthread', 'nbin', and 'niter' and also even reverting back to their default values, but RStudio still keeps crashing when running 'train'. However, I found that when the dim is set to be 50 or fewer, 'train' works just fine.

At first, I thought that this was the problem of computational resource. But since I'm running the script on 40-core 128GB-RAM machine and there was more than 60GB of RAM available just right before I ran the 'train', so I'm not sure the computational resource is the case.

Do you have any idea of why this happens? Could it be the parameter settings, or is the computational resource actually an issue, or could it be other reasons?

**Comment by yixuan** [comment]
Have you tried to run the script in a pure R environment without RStudio?
