### ISSUE TITLE
nan values in `rmse` and `obj`

### ISSUE THREAD

**Issue by L-1996-G** [yixuan/recosystem#20]
I am trying to develop recommendation model. I have implicit rating (which product bought user). I have about 18mln interaction. I use `recosystem` package to train model, but `rmse` and `obj` are `nan` (see on picture). why does model not converge? what may be problem?
![image](https://user-images.githubusercontent.com/63259309/166165497-a8c2ec75-e8de-4354-a142-f34ed574afec.png)

**Comment by yixuan** [comment]
Please consider to provide a reproducible example to reopen this issue.
