### ISSUE TITLE
Typo in the reference manual

### ISSUE THREAD

**Issue by diplomike** [yixuan/recosystem#21]
The code "data_file" on p.4 and p.6 of the reference manual should be "out_file" instead. The author has been notified about this and will fix it in the next update. 

In any case, would like to take this opportunity to give a big hand to this great algorithm.

**Comment by yixuan** [comment]
Thanks. Fixed in https://github.com/yixuan/recosystem/commit/23c9ce4ee9ec369239b55b8e484280c828965087.
