### ISSUE TITLE
Recommender system for implicit feedback?

### ISSUE THREAD

**Issue by nickresnick** [yixuan/recosystem#3]
Hi Yixuan-- your package is awesome! I've found it incredibly easy to use, and lightening-fast. This isn't really an issue, but more of a feature request.

I'm wondering if you could include the loss function for implicit feedback (equation 3 [in this paper](http://yifanhu.net/PUB/cf.pdf)) in a new release? The loss function uses c_ui \* (p_ui - x_u \* y_i)^2 instead of (r_ui - x_u \* y_i)^2 where p_ui = 1 if r_ui > 0, and 0 otherwise, and c_ui is a confidence parameter, usually defined as 1 + alpha \* r_ui.

**Comment by yixuan** [comment]
Hi @nickresnick , I think this is doable but requires some careful work. Currently `recosystem` is built upon the [LIBMF](http://www.csie.ntu.edu.tw/%7Ecjlin/libmf/) library, so to implement a new objective function the core C++ code needs to be modified. You can also try to contact the authors of LIBMF to see if they have any plan for this.
