### ISSUE TITLE
`train` freezes when running in parallel processes

### ISSUE THREAD

**Issue by vermouthmjl** [yixuan/recosystem#4]
Hi Yiyuan, thanks for your work on this wonderful package.

I know this issue is going to look like a stretch, but I'm still posting it here just in case an answer could come to surface.
Basically, this is the situation: I used `recosystem` as a benchmark with many other matrix completion/recovery methods in parallel on a 32-core machine. I run, say 10 matrix completions, in parallel using `mclapply`. At the end of each job, a model object is saved on the disk (`saveRDS`).
Whenever I throw `recosystem` into the mix, the whole script hangs after a certain number of time (never happens when `recosystem` is not used). None of the cores would be in use, but the script just hangs at the execution for hours, and no model object on the disk.
I was not able to produce this when I ran the same script with a single core.
I suspect that it's because LIBMF does some parallel computing that enters in conflict with the parallel jobs.

However, there are some catches:

- I actually used the 0.3 version of 2015-05-28, because I am not in a position to change the R installation of the machine.
- the matrix that I try to complete has very unbalanced entry values (typically that could violate the completion guarantee conditions).

Do you maybe have an idea as to why this happens? Could it be the parallel thing, or is the old version an issue, or could it be some other reason?

**Comment by yixuan** [comment]
Hi Jiali,
Before stepping into the details, I would suggest you first trying the 0.4 version. I know you cannot directly install it since it depends on R >= 3.3.0, but the trick is that you can manually download the source package and change its dependence to R >= 3.1.0. I had to use >= 3.3.0 because I needed to avoid it being checked by the old GCC compiler on CRAN.

**Comment by yixuan** [comment]
And by the way, the syntax of 0.4 has been changed so you may need to adjust your code a little bit.

**Comment by vermouthmjl** [comment]
Hey Yixuan.
Thanks for your reply. I tried your suggestion and installed the stable 0.4 version on CRAN of the package, but there was still the same problem.
I'll try to see if I could find a case where the problem can be reproduced and report back here.

**Comment by yixuan** [comment]
Sure. Let me know if I can provide any help.
