### ISSUE TITLE
Error when too many threads

### ISSUE THREAD

**Issue by Tutuchan** [yixuan/recosystem#6]
Hi,
I tried running recosystem on an EC2 instance with 32 cores and I ran into this error

```
Error in r$tune(ratings_train, opts = list(loss = "log", dim = c(10, 20,  : 
  number of bins must be greater than number of threads
```
which appears to stem from [this line](https://github.com/yixuan/recosystem/blob/master/src/mf.cpp#L3193).

I did not see a way to specify the number of bins from R. Could you add this possibility ? I'd be happy to submit a PR.

Thanks

**Comment by yixuan** [comment]
It seems I left this parameter out when writing the wrapper. I'll provide a patch later. Thanks!

**Comment by yixuan** [comment]
This has been fixed in the most recent version. I'll submit the package to CRAN shortly.
