### ISSUE TITLE
Install error on Ubuntu

### ISSUE THREAD

**Issue by RoyalTS** [yixuan/recosystem#7]
Trying to install the package I get the following error:

    > install.packages('recosystem', clean = FALSE)
    Installing package into ?/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4?
    (as ?lib? is unspecified)
    trying URL 'https://cran.rstudio.com/src/contrib/recosystem_0.4.2.tar.gz'
    Content type 'application/x-gzip' length 175301 bytes (171 KB)
    ==================================================
    downloaded 171 KB
    
    * installing *source* package ?recosystem? ...
    ** package ?recosystem? successfully unpacked and MD5 sums checked
    ** libs
    g++ -std=gnu++11 -I/farmshare/software/free/r/R-3.4.0/lib/R/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/RcppProgress/include" -I/usr/local/include  -fopenmp -fpic  -g -O2 -c mf.cpp -o mf.o
    g++ -std=gnu++11 -I/farmshare/software/free/r/R-3.4.0/lib/R/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/RcppProgress/include" -I/usr/local/include  -fopenmp -fpic  -g -O2 -c reco-output.cpp -o reco-output.o
    g++ -std=gnu++11 -I/farmshare/software/free/r/R-3.4.0/lib/R/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/RcppProgress/include" -I/usr/local/include  -fopenmp -fpic  -g -O2 -c reco-predict.cpp -o reco-predict.o
    g++ -std=gnu++11 -I/farmshare/software/free/r/R-3.4.0/lib/R/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/RcppProgress/include" -I/usr/local/include  -fopenmp -fpic  -g -O2 -c reco-read-data.cpp -o reco-read-data.o
    g++ -std=gnu++11 -I/farmshare/software/free/r/R-3.4.0/lib/R/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/RcppProgress/include" -I/usr/local/include  -fopenmp -fpic  -g -O2 -c reco-train.cpp -o reco-train.o
    g++ -std=gnu++11 -I/farmshare/software/free/r/R-3.4.0/lib/R/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/RcppProgress/include" -I/usr/local/include  -fopenmp -fpic  -g -O2 -c reco-tune.cpp -o reco-tune.o
    gcc -std=gnu99 -I/farmshare/software/free/r/R-3.4.0/lib/R/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I"/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/RcppProgress/include" -I/usr/local/include   -fpic  -g -O2 -flto -c register_routines.c -o register_routines.o
    g++ -std=gnu++11 -shared -L/farmshare/software/free/r/R-3.4.0/lib/R/lib -L/usr/local/lib -o recosystem.so mf.o reco-output.o reco-predict.o reco-read-data.o reco-train.o reco-tune.o register_routines.o -fopenmp -L/farmshare/software/free/r/R-3.4.0/lib/R/lib -lR
    installing to /afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/recosystem/libs
    ** R
    ** inst
    ** preparing package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** installing vignettes
    ** testing if installed package can be loaded
    Error: package or namespace load failed for ?recosystem? in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/recosystem/libs/recosystem.so':
      /afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/recosystem/libs/recosystem.so: file too short
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing ?/afs/.ir.stanford.edu/users/t/o/mydir/R/x86_64-pc-linux-gnu-library/3.4/recosystem?
    Warning in install.packages :
      installation of package ?recosystem? had non-zero exit status

`sessionInfo()`:

    > sessionInfo()
    R version 3.4.0 (2017-04-21)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 14.04.5 LTS
    
    Matrix products: default
    BLAS: /software/free/r/R-3.4.0/lib/R/lib/libRblas.so
    LAPACK: /software/free/r/R-3.4.0/lib/R/lib/libRlapack.so
    
    locale:
    [1] C
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base
    
    loaded via a namespace (and not attached):
    [1] compiler_3.4.0 tools_3.4.0

**Comment by AzatR** [comment]
Try installing using IDE RStudio. On the Packages tab, click Install and find recosystem

**Comment by yixuan** [comment]
Given that this is a very old issue, let me close it first. Feel free to reopen it if you encounter any problems for the latest version.
