### ISSUE TITLE
The order of the users/items in the output results

### ISSUE THREAD

**Issue by bellowswang** [yixuan/recosystem#8]
First thank you very much for your work on this great package.
What is the order of the users/items in the output results? Is it based on the order of the users/items I input into the model or is it based on their coding values?

**Comment by diplomike** [comment]
I tried it with the package's test data. The order of the resulting matrices is sorted by ascending order of the user/item ID respectively.

**Comment by yixuan** [comment]
Somehow I missed this issue long time ago. With the confirmation given by @diplomike, I think this issue can be closed.
